# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': 'https://atai.github.io',
                'git_url': 'https://github.com/atai/',
                'lib_path': ''},
  'syms': {'atai.core': {'atai.core.foo': ('core.html#foo', 'atai/core.py')}, 'atai.setup': {}}}
